[ubuntu_servers]
cloudflare-gateway ansible_host=LOCAL-IP ansible_user=USER

[debian_servers]
jellyfin ansible_host=LOCAL-IP ansible_user=USER

[fedora_servers]
kuma-homepage ansible_host=LOCAL-IP ansible_user=USER

[opensuse_servers]
technitium ansible_host=LOCAL-IP ansible_user=USER

[linux_servers:children]
ubuntu_servers
debian_servers
fedora_servers
opensuse_servers
