---
- import_playbook: update-apt.yml
- import_playbook: update-fedora.yml
- import_playbook: update-opensuse.yml
- import_playbook: update-proxmox.yml
- import_playbook: update-management.yml
- import_playbook: update-truenas.yml
